const sampleData = [
    {
        _id: "637d9683856b272166b77af8",
        email: "b122001@iiit-bh.ac.in",
        __v: 0,
        dataSet: true,
        imageSet: true,
        about: "Hello EVERYONE 👋👋 , I am abhik . I do have lots of interests in coding , PHOTOGRAPHY, and exploring New technologies and Would love to explore these in My college life . I love to play cricket and badminton. PLEASE feel free to contact me any TIME through my given handles . Would be happy to help anyone in leisure time . ",
        city: "Bhubaneswar",
        id: "b122001",
        name: "Abhik sundar sahu",
        state: "Odisha ",
        year: 1,
        instagram: "https://instagram.com/abhiksahu3092?igshid=YmMyMTA2M2Y=",
        linkedin: "https://www.linkedin.com/in/abhik-sundar-sahu-262179258",
        github: "https://github.com/Abhiksahu3092"
    },
    {
        _id: "638f7fe9780e3003eac41bf1",
        email: "b122002@iiit-bh.ac.in",
        __v: 0,
        dataSet: true,
        imageSet: true,
        about: "Hello everyone!! I am Abhimanyu. I love playing football,table tennis and chess.i am an ntse scholar and have a decent academic record.i also have keen Interest in debating and public speaking.hoping to learn,grow and have fun in these 4 years with you all.",
        city: "patna",
        id: "b122002",
        name: "Abhimanyu Kumar singh",
        state: "bihar",
        year: 1
    },
    {
        _id: "637d96af856b272166b78f86",
        email: "b122004@iiit-bh.ac.in",
        __v: 0,
        about: "YOU MAY CALL ME AS THE GURGAON WALA ODIA TOka. I HAVE A KEEN INTEREST IN CRICKET. AND PLAY TABLA OCASSIONALLY. Always Happpy to Help. ",
        city: "Bhubaneswar ",
        dataSet: true,
        id: "b122004",
        imageSet: true,
        name: "Abinas Ojha ",
        state: "Odisha",
        year: 1,
        instagram: "Https://instagram.com/abinas.ojha.264"
    },
    {
        _id: "63923429780e3003eae76be8",
        email: "b122006@iiit-bh.ac.in",
        __v: 0,
        about: "Hello everyone 👋👋, I am Adarsh. I have lots OF interest in coding and reading books. I love to play chess and cricket.",
        city: "Kanpur",
        dataSet: true,
        id: "b122006",
        imageSet: true,
        name: "Adarsh tiwari",
        state: "Uttar PRADESH",
        year: 1,
        linkedin: "HTTPS://LINKEDIN.COM/ADARSH TIWARI"
    },
    {
        _id: "637c4780856b27216644c776",
        email: "b122008@iiit-bh.ac.in",
        __v: 0,
        dataSet: true,
        imageSet: true,
        about: "🎮 Gamo-sapien🕹\nComic geek 👓 \nFootball ⚽⚽ lover \nWho doesn't like anime\n",
        city: "Berhampur ",
        id: "b122008",
        instagram: "https://instagram.com/ashen_aditya?igshid=NmQ2ZmYxZjA=",
        name: "Aditya Narayan",
        state: "Odisha ",
        year: 1,
        github: "https://github.com/aditARAN",
        linkedin: "https://www.linkedin.com/in/aditya-narayan-8b40b0258"
    },
    {
        _id: "637f2dfc856b27216649e55b",
        email: "b122009@iiit-bh.ac.in",
        __v: 0,
        dataSet: true,
        imageSet: true,
        about: "Bonjour fellas!A heliophile dis side.My hobbies include dancing, journaling, playing guitar, badminton,chess and reading books.WOULD love to know about you too!",
        city: "Cuttack",
        id: "b122009",
        name: "Adyasha mohanty",
        state: "Odisha",
        year: 1,
        instagram: "addyctive.16"
    },
    {
        _id: "637d91cd856b272166b5ae6d",
        email: "b122010@iiit-bh.ac.in",
        __v: 0,
        about: "Hello 👋,  I am akash bharti. My id is B122010. I am from ranchi. My hobbies are watching movies and playing games and f1. Not much😅",
        city: "RANCHI",
        dataSet: true,
        id: "b122010",
        imageSet: true,
        linkedin: "https://www.linkedin.com/in/akash-bharti-56598b199",
        name: "Akash bharti",
        state: "JHARKHAND",
        year: 1,
        instagram: "https://www.instagram.com/invites/contact/?i=90mn0ljguule&utm_content=pa5w4od"
    },
    {
        _id: "637dc908856b272166ca16ff",
        email: "b122011@iiit-bh.ac.in",
        __v: 0,
        dataSet: true,
        imageSet: true,
        about: "Kudos! Myself Akshat bankey…..an average weeb and a gamer with hobbies including football and table tennis.",
        city: "Mumbai",
        id: "b122011",
        instagram: "https://instagram.com/bankeyboi._",
        name: "Akshat bankey",
        state: "Maharashtra",
        year: 1
    },
    {
        _id: "637c526e856b27216648da52",
        email: "b122012@iiit-bh.ac.in",
        __v: 0,
        dataSet: true,
        imageSet: true,
        about: "I have keEn interest in photography,videography,editing,coding,and sports😊😊\n\n\n\n\n\nint main(){\n    Cout<<“hello everyone!!<<endl;\n}",
        city: "Delhi",
        id: "b122012",
        instagram: "https://www.instagram.com/_aman_raY_",
        name: "AMAN RAY",
        state: "Delhi",
        year: 1
    },
    {
        _id: "637dcc8a856b272166cb7742",
        email: "b122013@iiit-bh.ac.in",
        __v: 0,
        dataSet: true,
        imageSet: true,
        about: "Hi, my name is Amarendra Das and I come from a middle-class village background. I have a great aim in technology and am passionate about achieving my goals. Despite facing many failures, I remain resilient and determined to succeed.",
        city: "DHENKANAL",
        id: "b122013",
        name: "Amarendra das ",
        state: "ODISHA",
        year: 1,
        linkedin: "https://www.linkedin.com/in/amarendra-das-5548aa25a"
    },
    {
        _id: "637ee8be856b27216630483a",
        email: "b122014@iiit-bh.ac.in",
        __v: 0,
        dataSet: true,
        imageSet: true,
        about: "Hello,I am amisha Ray.my id is b122014.i have interest in listening to music,travelling and watching movies.",
        city: "Bhubaneswar ",
        id: "b122014",
        instagram: "__amisha_ray__",
        name: "Amisha ray",
        state: "Odisha",
        year: 1
    },
    {
        _id: "637e1e5a856b272166ea3e7e",
        email: "b122015@iiit-bh.ac.in",
        __v: 0,
        dataSet: true,
        imageSet: true,
        about: "Intuitive, curious and a learner. My motto - \"take it live it.\" Interests in basketball 🏀 and also a writer. I am rather intrigued by phenomenal happenings.be a event and everyone will be looking forward to you 👒",
        city: "angul",
        id: "b122015",
        instagram: "https://www.instagram.com/am_13_it/",
        linkedin: "https://www.linkedin.com/in/amit-kumar-73a257258",
        name: "Amit kumar behera",
        state: "odisha",
        year: 1
    },
    {
        _id: "637dca8e856b272166caa8f1",
        email: "b122016@iiit-bh.ac.in",
        __v: 0,
        dataSet: true,
        imageSet: true,
        about: "Live young live free....",
        city: "Bhubaneshwar",
        id: "b122016",
        instagram: "HTTPS://INSTAGRAM.COM/routamit572 ",
        name: "Amit Kumar Rout ",
        state: "ODISHA",
        year: 1
    },
    {
        _id: "637d9693856b272166b78388",
        email: "b122017@iiit-bh.ac.in",
        __v: 0,
        dataSet: true,
        imageSet: true,
        about: "Ready to learn and EXPLORE.like to play volleyball and a huge football fan.\n\nAdios.✌️",
        city: "Jharsuguda ",
        id: "b122017",
        name: "Anand Naik",
        state: "Odisha",
        year: 1,
        instagram: "Https://instagram.com/_ANDY_nic_"
    },
    {
        _id: "637c521c856b27216648ba18",
        email: "b122018@iiit-bh.ac.in",
        __v: 0,
        dataSet: true,
        imageSet: true,
        about: "Hi EVERYBODY, I am Anirudh. A guy having a keen interest in watching movies, TRAVELLING, listening to PODCASTS and writing programs in the mean time... \nWANNA know more about me?! HERE are my handles.",
        city: "Jaipur ",
        id: "b122018",
        name: "Anirudh Pradhan ",
        state: "Rajasthan ",
        year: 1,
        instagram: "https://www.instagram.com/_.anirudh.roshan._/",
        linkedin: "https://www.linkedin.com/in/anirudh-pradhan-a2ab25245"
    },
    {
        _id: "637e0676856b272166e0ac9c",
        email: "b122019@iiit-bh.ac.in",
        __v: 0,
        about: "Always be happy\n",
        city: "Haldia",
        dataSet: true,
        id: "b122019",
        imageSet: true,
        instagram: "https://instagram.com/showd259?igshid=Njc5ZjliZWU=",
        name: "Ankan barik",
        state: "West bengal",
        year: 1
    },
    {
        _id: "637e1fe0856b272166eae55a",
        email: "b122020@iiit-bh.ac.in",
        __v: 0,
        dataSet: true,
        imageSet: true,
        about: "When they try to burn you down with a couple of matches, \nJust remember you're a Phoenix rising from the ASHES!! ",
        city: "Howrah",
        id: "b122020",
        instagram: "https://instagram.com/simply._sophisticated?igshid=YmMyMTA2M2Y=",
        name: "Ankit Gourisaria",
        state: "West Bengal",
        year: 1
    },
    {
        _id: "637dceb2856b272166cc5241",
        email: "b122021@iiit-bh.ac.in",
        __v: 0,
        about: "hola!!\ni am An ambivert and an explorer who loves to perceive a unique way to introduce life...\n",
        city: "cuttack",
        dataSet: true,
        id: "b122021",
        imageSet: true,
        instagram: "J_ankita12",
        linkedin: "ankita jena",
        name: "ankita jena",
        state: "odisha",
        year: 1
    },
    {
        _id: "637f199e856b272166426bcb",
        email: "b122022@iiit-bh.ac.in",
        __v: 0,
        dataSet: true,
        imageSet: true,
        about: "Learning, observing, and connecting the dots",
        city: "Bhawanipatna ",
        id: "b122022",
        instagram: "https://instagram.com/anushkajoshi301?igshid=YmMyMTA2M2Y=",
        name: "Anushka Joshi",
        state: "Odisha ",
        year: 1
    },
    {
        _id: "637e3dd3856b272166f628ea",
        email: "b122023@iiit-bh.ac.in",
        __v: 0,
        about: "I would like to introduce myself! I am Anwesha Behera.A positive thinker and like to communicate with people. My interests are based on computer science which includes numerical methods,  programming and machine learning. Thank you",
        city: "Berhampur ",
        dataSet: true,
        id: "b122023",
        imageSet: true,
        instagram: "Sansa_2004",
        name: "Anwesha behera ",
        state: "Odisha ",
        year: 1
    },
    {
        _id: "637c4634856b272166443ba4",
        email: "b122024@iiit-bh.ac.in",
        __v: 0,
        about: "Khud ko jan Lo...mereko jan ke kuch fayda nahi ...mujhe khud nahi pata mere bare ME🙂\n#introvert✌️...jab tak hamare level ka koi bakchod nahi MILTA.\nLearning through semesters, learning++",
        city: " murshidabad ",
        dataSet: true,
        id: "b122024",
        imageSet: true,
        name: "Aritra mondal",
        state: "West Bengal ",
        year: 1,
        instagram: "https://instagram.com/aritramondal_2002?igshid=YmMyMTA2M2Y=",
        linkedin: "https://www.linkedin.com/in/aritra-mondal-730722258"
    },
    {
        _id: "637e4fca856b272166fd7042",
        email: "b122025@iiit-bh.ac.in",
        __v: 0,
        about: "Hello everyone!I am Arya singh. i enjoy playing PC games, listening to rap songs and following Geopolitics.i would love to be a Cyber GEEK and pursue a career in coding and software development.i was a district level boxer and I can also play cricket, badminton and KABBADI too.\nPeace out",
        city: "Prayagraj ",
        dataSet: true,
        id: "b122025",
        imageSet: true,
        instagram: "Https://instagram.com/Arya.singh.bais",
        name: "Arya Singh ",
        state: "Uttar Pradesh ",
        year: 1
    },
    {
        _id: "637e77a3856b2721660befc8",
        email: "b122026@iiit-bh.ac.in",
        __v: 0,
        dataSet: true,
        imageSet: true,
        about: "Hello guys,\nWelcome to my profile. \nAn enthusiastic GUY of programming & a quick learner......\nEager to explore about new things.......\nStudy is my passion and spirituality is a part of my life.....\nAlways believe in \"Arise awake and stop not till the goal is achieved.\"\n",
        city: "Balasore ",
        id: "b122026",
        instagram: "Https://Instagram.com/aryanpatra7 ",
        name: "ARYAMAN PATRA",
        state: "Odisha ",
        year: 1
    },
    {
        _id: "637dd5d5856b272166ceebec",
        email: "b122027@iiit-bh.ac.in",
        __v: 0,
        dataSet: true,
        imageSet: true,
        about: "Good-acting person",
        city: "cuttack",
        id: "b122027",
        name: "ashutos Aditya Das",
        state: "odisha",
        year: 1,
        instagram: "https://www.instagram.com/ashutos_das1206/"
    },
    {
        _id: "637ebded856b2721662216d0",
        email: "b122028@iiit-bh.ac.in",
        __v: 0,
        dataSet: true,
        imageSet: true,
        about: "Hello!\nThis is Astha sharma here.i am native of himachal pradesh but had done my 12th from angul odisha.i am a poetic person and would be eager to interact with every new face I meet.currently exploring CSE in order to know my strengths and faults in the subject.",
        city: "Angul ",
        id: "b122028",
        instagram: "https://www.instagram.com/astha21sharma/",
        linkedin: "https://www.linkedin.com/in/astha-sharma-a49932257",
        name: "astha sharma",
        state: "Odisha ",
        year: 1
    },
    {
        _id: "63b71444780e3003ea517674",
        email: "b122029@iiit-bh.ac.in",
        __v: 0,
        dataSet: true,
        imageSet: true,
        about: "... Facing every thing with a smile...",
        city: "Dhenkanal ",
        id: "b122029",
        name: "Asutosh Kataruka ",
        state: "Odisha ",
        year: 1
    },
    {
        _id: "6415d805c6af4807b98f60fb",
        email: "b122030@iiit-bh.ac.in",
        __v: 0,
        dataSet: true,
        imageSet: true,
        about: "Hello everyone I am Suraj\nI don't care what people THINK about me",
        city: "Guntur",
        id: "b122030",
        instagram: "Suraj_atchuta",
        name: "Atchuta Mohan Venkata Suraj",
        state: "Andhra Pradesh ",
        year: 1
    },
    {
        _id: "637c4658856b2721664449d3",
        email: "b122031@iiit-bh.ac.in",
        __v: 0,
        dataSet: true,
        imageSet: true,
        about: "Hello, I am Ayushman from cse BRANCH. i am so much interested to learn CODING 🧑‍💻 and love to play mobile games 💖.",
        city: "Bhubaneswar ",
        id: "b122031",
        name: "Ayushman patro",
        state: "ODISHA",
        year: 1
    },
    {
        _id: "637ce11f856b2721667ca2b3",
        email: "b122032@iiit-bh.ac.in",
        __v: 0,
        dataSet: true,
        imageSet: true,
        about: "Myself bkbandana from cseA .basically from odisha only,my Id is b122032. A keen learner ,zealous and liable too\nLoves listening to musics ,travelling , exploring new THINGS and gardening ..interested in coding and sometimes manages to dance well..\nThank u",
        city: "Bhubaneswar ",
        id: "b122032",
        instagram: "HTTPS://Instagram.com/In/@bandan.aa11 ",
        linkedin: "HTTPS://LINKEDIN.COM/IN/BKBANDANA",
        name: "B K BANDANA ",
        state: "Odisha ",
        year: 1
    },
    {
        _id: "637e2188856b272166eb948a",
        email: "b122033@iiit-bh.ac.in",
        __v: 0,
        dataSet: true,
        imageSet: true,
        about: "I am an otaku who loves to watch anime.i get nervous SOMETIMEs because i am an introvert.i am also like music and playing badminton ",
        city: "Musabani",
        id: "b122033",
        name: "Baldev Singh",
        state: "Jharkhand ",
        year: 1,
        instagram: "https://www.instagram.com/baldevsingh1719"
    },
    {
        _id: "637dae0c856b272166c02334",
        email: "b122034@iiit-bh.ac.in",
        __v: 0,
        dataSet: true,
        imageSet: true,
        about: "Hello everyone\nI am Bedasnata das.\nLove reading novels and listening to music.\nwould love to travel the WORLD someday.\nHope we get along well.",
        city: "Bhubaneswar ",
        id: "b122034",
        instagram: "https://www.instagram.com/",
        name: "Bedasnata Das",
        state: "Odisha",
        year: 1
    },
    {
        _id: "637d9ac9856b272166b94f14",
        email: "b122035@iiit-bh.ac.in",
        __v: 0,
        dataSet: true,
        imageSet: true,
        about: "Careless Hutiya\n",
        city: "Palwal ",
        id: "b122035",
        instagram: "https://instagram.com/ashu.singh.12?igshid=YmMyMTA2M2Y=",
        name: "Bharat Bhushan ",
        state: "Haryana ",
        year: 1
    },
    {
        _id: "637e01b7856b272166ded212",
        email: "b122036@iiit-bh.ac.in",
        __v: 0,
        dataSet: true,
        imageSet: true,
        about: "Oh hey there.\n",
        city: "Krishnagar",
        id: "b122036",
        instagram: "Https://instagram.com/rad_fellow",
        name: "Bibek pathak",
        state: "West Bengal",
        year: 1
    },
    {
        _id: "637e2c4b856b272166efae46",
        email: "b122037@iiit-bh.ac.in",
        __v: 0,
        about: "I am bibhuprasad dash from jagatsinghpur,ODISHA.currently pursuing my btech  degree in iiit Bhubaneswar. I have completed  my intermediate in chse from college of basic science and humanities, Bhubaneswar. I like to play cricket and badminton and some indoor games also. I also like to watch some fantasy movies. ",
        city: "Jagatsinghpur",
        dataSet: true,
        id: "b122037",
        imageSet: true,
        instagram: "https://instagram.com/bpdash176?igshid=YmMyMTA2M2Y=",
        name: "BIBHUPRASAD DASH",
        state: "Odisha",
        year: 1
    },
    {
        _id: "637ddae7856b272166d0d6f7",
        email: "b122038@iiit-bh.ac.in",
        __v: 0,
        dataSet: true,
        imageSet: true,
        about: "Hello everyone, I am from baripada, Odisha but I stay in Raipur, Chattisgarh. I have interest in playing chess and cricket. I am interested in coding and want to learn many things in these 4 years .",
        city: "Baripada",
        id: "b122038",
        instagram: "https://instagram.com/_binashak_?igshid=YmMyMTA2M2Y=",
        name: "Binashak Mohanty",
        state: "Odisha",
        year: 1
    },
    {
        _id: "637e3e6a856b272166f66241",
        email: "b122039@iiit-bh.ac.in",
        __v: 0,
        dataSet: true,
        imageSet: true,
        about: "my I'd is b122039.a little INTROVERT.LOves playing cricket.",
        city: "Jajpur",
        id: "b122039",
        name: "Biswa Prakash Dalai",
        state: "odisha",
        year: 1
    },
    {
        _id: "637c47a4856b27216644d6c8",
        email: "b122040@iiit-bh.ac.in",
        __v: 0,
        dataSet: true,
        imageSet: true,
        about: "I am from Telangana\nA boy with some dreams and friends ",
        city: "suryapet",
        id: "b122040",
        instagram: "https://instagram.com/abhiram._.034?igshid=NDk5N2NlZjQ=",
        name: "ABHIRAM ",
        state: "Telangana",
        year: 1
    },
    {
        _id: "637dc0d4856b272166c6cadf",
        email: "b122041@iiit-bh.ac.in",
        __v: 0,
        dataSet: true,
        imageSet: true,
        about: "Loading...",
        city: "Birsinghpur pali",
        github: "https://github.com/Brijendra-Singh2003",
        id: "b122041",
        instagram: "https://instagram.com/brijendra361?igshid=ZGUzMzM3NWJiOQ==",
        linkedin: "https://www.linkedin.com/in/brijendra-singh-047400241",
        name: "Brijendra Singh ",
        state: "Madhya Pradesh",
        year: 1
    },
    {
        _id: "63a751be780e3003eae09c0a",
        email: "b122042@iiit-bh.ac.in",
        __v: 0,
        about: "          <Baaghi.h>\nmain()\n{ HELLO..i am chandan KUMAR and I'm from PATNA,BIHAR.i like to do gymnasts and PROGRAMMING.I don't think much about the future, I live and enjoy my present.THAT'S all my HONOR!\n     Point to be NOTED!|My nickname is baaghi|\n        DHANYABAD!!!\n}",
        city: "Patna",
        dataSet: true,
        id: "b122042",
        imageSet: true,
        instagram: "https://www.instagram.com/baaghi_chandan",
        name: "Chandan kumar ",
        state: "Bihar",
        year: 1
    },
    {
        _id: "637df9ec856b272166dc061a",
        email: "b122043@iiit-bh.ac.in",
        __v: 0,
        about: "Myself chatura peketi.I am from Andhra pradesh.\nMy ID no:B122043.I am interest in playing chess",
        city: "Vizianagaram",
        dataSet: true,
        id: "b122043",
        imageSet: true,
        name: "Chatura peketi",
        state: "Andhra pradesh",
        year: 1
    },
    {
        _id: "637c320c856b2721663cfa83",
        email: "b122044@iiit-bh.ac.in",
        __v: 0,
        dataSet: true,
        imageSet: true,
        about: "Hello everyone, my name is Chinmaya Kumar Sahoo, my ID is B122044 and I'm from btech cse-A. My hobbies are cubing and I like watching Hollywood movies, Japanese anime and listening to English songs with a few exception of Bollywood songs. I also like TO play badminton and basketball.",
        city: "Durgapur ",
        id: "b122044",
        instagram: "https://instagram.com/demon_slayer_chini?igshid=MWM2YjBjM2Q=",
        linkedin: "https://www.linkedin.com/in/chinmaya-sahoo-b47385254",
        name: "Chinmaya Kumar Sahoo ",
        state: "West Bengal ",
        year: 1
    },
    {
        _id: "637dc9df856b272166ca6717",
        email: "b122045@iiit-bh.ac.in",
        __v: 0,
        dataSet: true,
        imageSet: true,
        about: "I am a highly motivated and individual with a passion for learning and problem-solving.I am excited to see where my education and experiences will take me and am committed to making the most of every opportunity that comes my way.\n©MESSI>>>>>>>>RONALDO\nMESSI IS THE 🐐",
        city: "Kolkata",
        id: "b122045",
        name: "Devjit sikdar",
        state: "West Bengal ",
        year: 1,
        instagram: "https://www.instagram.com/invites/contact/?i=16njswlyrwngl&utm_content=g5vm3kf"
    },
    {
        _id: "637da17b856b272166bbbc7c",
        email: "b122046@iiit-bh.ac.in",
        __v: 0,
        dataSet: true,
        imageSet: true,
        about: "I have done my 10th from St.Agnes School and 12th from BNR Excellence Academy,Kharagpur,WB.\n\nAn average Human who loves watching Anime and listens to MUSIC.",
        city: "Kharagpur ",
        id: "b122046",
        instagram: "https://www.instagram.com/dulariiiii/",
        name: "Dulari Majhi",
        state: "West Bengal ",
        year: 1
    },
    {
        _id: "637e3a49856b272166f4e241",
        email: "b122047@iiit-bh.ac.in",
        __v: 0,
        about: "Hello EVERYONE, i am RUSHIK. I love Travelling and am fond of MOVIES and I am good CALIGRAPHER .EthusAstic In Coding and ROBOTICS(Recent learner).\n I am an avid SINGer and am INTERESTED in reasearch and DEVELOPMENT. 🤞",
        city: "Srikakulam ",
        dataSet: true,
        id: "b122047",
        imageSet: true,
        instagram: "HTTps://Instagram.com/Rushik_ram_forever",
        name: "DUmpala Rushik",
        state: "Andhra Pradesh ",
        year: 1,
        github: "",
        linkedin: "Https://linkedin.Com/Rushik-Dumpala "
    },
    {
        _id: "637d93d6856b272166b65d85",
        email: "b122048@iiit-bh.ac.in",
        __v: 0,
        dataSet: true,
        imageSet: true,
        about: "#TECH ENTHUSIAST   #SINGER   #FINE ARTIST\n\n#LOVE BADMINTON    #EXPERT IN VEDIOGRAPHY\n\n#ANIME LOVER       #LOVE TO MAKE FRIENDS",
        city: "Bhubaneswar",
        github: "https://github.com/Venkatknight2295",
        id: "b122048",
        instagram: "https://instagram.com/gnvenkatpathiraju?igshid=YmMyMTA2M2Y=",
        name: "G naga venkat pathi raju",
        state: "Odisha",
        year: 1
    },
    {
        _id: "637e55b2856b272166ffcd81",
        email: "b122050@iiit-bh.ac.in",
        __v: 0,
        dataSet: true,
        imageSet: true,
        about: "An ambivert with a love for moon and dance✨",
        city: "Balasore",
        id: "b122050",
        instagram: "https://www.instagram.com/hitashapadhi/",
        linkedin: "https://www.linkedin.com/in/hitasha-padhi-a68b14257",
        name: "Hitasha Padhi",
        state: "Odisha",
        year: 1
    },
    {
        _id: "637d976b856b272166b7ea19",
        email: "b122051@iiit-bh.ac.in",
        __v: 0,
        dataSet: true,
        imageSet: true,
        about: "HEY✌️ !!! U seem INTERESTED👀, why not approach me in class or anywhere offline ☕🍻",
        city: "Balasore ",
        id: "b122051",
        name: "Hrushikesh Barik ",
        state: "Odisha ",
        year: 1
    },
    {
        _id: "63959cfc780e3003eaefc387",
        email: "b122052@iiit-bh.ac.in",
        __v: 0,
        dataSet: true,
        imageSet: true,
        about: "Don't love and cry just fuck and fly 👊, (cricket lover)",
        city: "Midnapore",
        id: "b122052",
        name: "Indraneel Dey",
        state: "West Bengal",
        year: 1
    },
    {
        _id: "637c41a1856b272166425bf0",
        email: "b122053@iiit-bh.ac.in",
        __v: 0,
        dataSet: true,
        imageSet: true,
        about: "Hi Friends, I AM ippili yaswanth kumar FROM CSE-a.i LOVe to play BADMINTON, CHESS, WATCHING movies.i can speak english and telugu only. HOPE we make beautiful memories within these four years.\nthank you...",
        city: "rayagada",
        id: "b122053",
        name: "Ippili Yaswanth kumar",
        state: "odisha",
        year: 1,
        instagram: "https://www.instagram.com/yaswanth_ippili",
        linkedin: "www.linkedin.com/in/yaswanth-ippili-yash700"
    },
    {
        _id: "637e109a856b272166e4a2ac",
        email: "b122054@iiit-bh.ac.in",
        __v: 0,
        dataSet: true,
        imageSet: true,
        about: "Hey everyone.... I am Ipshita, a keen observer and LEARNER, would love to explore new things. Have interest in art, music and movies. ",
        city: "Berhampur ",
        id: "b122054",
        instagram: "https://www.instagram.com/ipshita._.19/",
        name: "Ipshita Patro",
        state: "Odisha ",
        year: 1
    },
    {
        _id: "637ed8a8856b2721662ada98",
        email: "b122055@iiit-bh.ac.in",
        __v: 0,
        dataSet: true,
        imageSet: true,
        about: "I LOVE TO TRAVEL AND EXPLORE THINGS.GOOD FOR THOSE WHO ARE GOOD WITH ME.CURIOUS TO LEARN NEW THINGS AND CODING.HOBBIES CAN'T BE EXPLAIN BUT I LOVE DOING ARTS AND CRAFTING.",
        city: "PARALAKHEMUNDI, Gajapati ",
        id: "b122055",
        instagram: "https://instagram.com/iconic_ipsi?igshid=ZDdkNTZiNTM=",
        name: "Ipsita Hota",
        state: "Odisha",
        year: 1
    },
    {
        _id: "637c3068856b2721663c785d",
        email: "b122056@iiit-bh.ac.in",
        __v: 0,
        about: "... Don't Contact...",
        city: "Puri",
        dataSet: true,
        id: "b122056",
        imageSet: true,
        instagram: "Https://instagram.com/IS_ISHAN.SINGH",
        name: "Ishan singh",
        state: "Odisha",
        year: 1,
        github: "Https://GITHUB.com/ishan5529",
        linkedin: "Https://LINKEDIN.com/in/ishan2004"
    },
    {
        _id: "637cfd0c856b272166866815",
        email: "b122057@iiit-bh.ac.in",
        __v: 0,
        dataSet: true,
        imageSet: true,
        about: "I am jeevan jyoti sahoo.\nI secured \n95.2 percent in 10th Cbse board &\n92 percent in 12 cbse with\nJee rank 27,134.\nI like interacting with PEople, especially seniors.\n\nI show awarness towards nature & am a fun loving guy. I am a very entertaining person.\n\n",
        city: "BHUBANESWAR",
        id: "b122057",
        name: "Jeevan Jyoti Sahoo",
        state: "Odisha",
        year: 1,
        instagram: "https://www.instagram.com/monsterjeevanjyotisahoo/"
    },
    {
        _id: "638ccd62780e3003ead8add9",
        email: "b122059@iiit-bh.ac.in",
        __v: 0,
        dataSet: true,
        imageSet: true,
        about: "A_£EARN€R_and_BEGINNE® of_EXPLORER,UN©ONDITIONAL £over_and_living-in A_HA©KING_W¢RLD.INT®ested in HACKING..£",
        city: "Chittoor",
        id: "b122059",
        name: "K Gnanendra Reddy",
        state: "Andhra pradesh",
        year: 1,
        instagram: "HTTPS://Instagram.com/PROFONDEMENT_AIME/ "
    },
    {
        _id: "637d9a41856b272166b913eb",
        email: "b122060@iiit-bh.ac.in",
        __v: 0,
        dataSet: true,
        imageSet: true,
        about: "HELLO EVERYONE! I AM KAUSHIKA DASH FROM BTECH FIRST YEAR OF CSE BRANCH, BEARING ID NUMBER B122060.I AM FROM BHUBANESWAR.I COMPLETED MY 10TH FROM LOYOLA SCHOOL, BHUBANESWAR AND MY 12TH FROM MOTHERS PUBLIC SCHOOL, BHUBANESWAR.HOPE WE HAVE A GOOD TIME TOGETHER.",
        city: "BHUBANESWAR",
        id: "b122060",
        name: "KAUSHIKA DASH",
        state: "ODISHA",
        year: 1,
        instagram: "https://instagram.com/_kaushikadash_?igshid=YmMyMTA2M2Y="
    },
    {
        _id: "637ee2d3856b2721662e3cb5",
        email: "b122061@iiit-bh.ac.in",
        __v: 0,
        dataSet: true,
        imageSet: true,
        about: "Livin' within books, music and coding...",
        city: "Rourkela",
        id: "b122061",
        instagram: "https://instagram.com/khushi.5_?igshid=YmMyMTA2M2Y=",
        name: "Khushi Kispotta ",
        state: "Odisha ",
        year: 1
    },
    {
        _id: "637e3c02856b272166f57c21",
        email: "b122062@iiit-bh.ac.in",
        __v: 0,
        dataSet: true,
        imageSet: true,
        about: "Hello everyone this is komal BAGGU. I AM an ambivert and interested in watching movies, playing badminton  and in hosting events.",
        city: "Srikakulam ",
        id: "b122062",
        instagram: "Https://instagram.com/iam_komal.07",
        name: "Komal baggu",
        state: "Andhra Pradesh ",
        year: 1,
        github: "",
        linkedin: ""
    },
    {
        _id: "637d9542856b272166b6f93a",
        email: "b122064@iiit-bh.ac.in",
        __v: 0,
        dataSet: true,
        imageSet: true,
        about: "...",
        city: "Baleshwar ",
        id: "b122064",
        instagram: "https://www.instagram.com/lopa_6751?r=nametag",
        linkedin: "https://www.linkedin.com/in/leela-lopamudra-das-9299a4252",
        name: "Lila Lopamudra Das ",
        state: "Odisha ",
        year: 1
    },
    {
        _id: "637e1785856b272166e74cf3",
        email: "b122065@iiit-bh.ac.in",
        __v: 0,
        about: "Hey Guys, Myself LIRON SARANGI, i AM BASICALLY A MUSIC eNTHUSIAST, chess player and anime lover...... I LOVE LISTENING TO RAPS CREATING MUSIC, ESPECIALLY TRAP AND DUBSTEP.. OHH DID I FORGET TO MENTION?? i'M A BEATBOXER TOO!  ",
        city: "Bhubaneswar",
        dataSet: true,
        id: "b122065",
        imageSet: true,
        linkedin: "HTTPS://LINKEDIN.COM/IN/SARANGI-LIRON",
        name: "LIRON SARANGI",
        state: "odisha",
        year: 1,
        instagram: "https://www.instagram.com/down2hell_beatbox/"
    },
    {
        _id: "637da8f3856b272166be6579",
        email: "b122066@iiit-bh.ac.in",
        __v: 0,
        dataSet: true,
        imageSet: true,
        about: "I love traveling to new places, intrested in playing volleyball, love coding, finally ambitious guy to learn new skills.be hard at your work every happiness comes to you. ",
        city: "Ongole",
        id: "b122066",
        name: "Maddineni Vishnu ",
        state: "ANDHRA Pradesh ",
        year: 1,
        instagram: "Https://instagram.com/____life_hacker_24"
    },
    {
        _id: "637dc005856b272166c67f8b",
        email: "b122067@iiit-bh.ac.in",
        __v: 0,
        dataSet: true,
        imageSet: true,
        about: "Hello Everyone,,I am Maheswar Mahapatra. I love to explore new things. I have interest in app development and competitive coding.",
        city: "Bhubaneswar",
        id: "b122067",
        name: "Maheswar Mahapatra",
        state: "Odisha",
        year: 1
    },
    {
        _id: "637dffb5856b272166de1738",
        email: "b122068@iiit-bh.ac.in",
        __v: 0,
        dataSet: true,
        imageSet: true,
        about: "A Learner and EXPLORER, living in the moment \n",
        city: "Bhubaneswar ",
        id: "b122068",
        instagram: "https://instagram.com/m.a.n.y.a.t.a?igshid=MWM2YjBjM2Q=",
        name: "Manyata patra",
        state: "ODISHA ",
        year: 1
    },
    {
        _id: "637ddbc4856b272166d1276a",
        email: "b122069@iiit-bh.ac.in",
        __v: 0,
        about: "Currently Exploring new things and learning..\nStraight FORWARD,\nDoesn't like drama at all",
        city: "Agra",
        dataSet: true,
        id: "b122069",
        imageSet: true,
        instagram: "https://instagram.com/sikarwarmayank_04?igshid=YmMyMTA2M2Y=",
        name: "Mayank sikarwar",
        state: "Uttar Pradesh ",
        year: 1
    },
    {
        _id: "637dccd9856b272166cb9a75",
        email: "b122070@iiit-bh.ac.in",
        __v: 0,
        dataSet: true,
        imageSet: true,
        about: "Loading.....",
        city: "Guwahati ",
        id: "b122070",
        instagram: "https://instagram.com/__.tn.br.__?igshid=YzgyMTM2MGM=",
        linkedin: "https://www.linkedin.com/in/tanbir-ahmed-617185237",
        name: "MD TANBIR AHMED ",
        state: "Assam ",
        year: 1
    },
    {
        _id: "637dc4a8856b272166c85874",
        email: "b122071@iiit-bh.ac.in",
        __v: 0,
        about: "HELLO EVERYONE , I AM MRUDUL MAYANK MOHANTY. I am enthusiastic about CODING AND EXPLORING NEW places AND WOULD LOVE TO EXPLORE THESE IN MY COLLEGE LIFE . I LOVE TO PLAY BADMINTON AND CHESS. PLEASE do not hesitate to contact me if I could be of any help. 😄",
        city: "Bhubaneswar",
        dataSet: true,
        id: "b122071",
        imageSet: true,
        instagram: "HTTPS://INSTAGRAM.COM/___m3.nemesis___",
        linkedin: "https://www.linkedin.com/in/mrudul-mohanty-97a73024a",
        name: "Mrudul mayank mohanty",
        state: "Odisha",
        year: 1
    },
    {
        _id: "637cb95b856b2721666e0147",
        email: "b122072@iiit-bh.ac.in",
        __v: 0,
        dataSet: true,
        imageSet: true,
        about: "I'd - B122072\n\nBasically an ENTHUSIAST 😎,EXPLORER 😁,OBSERVER 🧠\n\nDid my SCHOOLing from st.marys SCHOOL,jajpur road\n\nIN QUEST FOR FUN 🤙📸\n\nGreat interest in sports🏏⚽✌️, been a gym freak\n\n(MSDIAN#07)❤️",
        city: "JAJPUR ROAD",
        id: "b122072",
        instagram: "https://instagram.com/nayan._.m05?igshid=YmMyMTA2M2Y=",
        name: "Nayan Mohanty",
        state: "Odisha",
        year: 1,
        linkedin: "https://www.linkedin.com/in/nayan-mohanty-805707258"
    },
    {
        _id: "637e417b856b272166f79cdb",
        email: "b122074@iiit-bh.ac.in",
        __v: 0,
        about: "Hello everyone myself Nihar Ranjan DAS having id:B122074.i am currently pursuing my BTech in Computer science and engineering. My hobbies are reading books and LISTENINg  MUSIC.i HAVE an interest in coding.",
        city: "BALASORE",
        dataSet: true,
        id: "b122074",
        imageSet: true,
        name: "Nihar Ranjan Das",
        state: "Odisha",
        year: 1,
        instagram: "https://instagram.com/nihardas0611?igshid=NjNlMDhmYTc=",
        linkedin: "https://www.linkedin.com/in/nihar-ranjan-das-8b271425a"
    },
    {
        _id: "637dcd74856b272166cbdcd2",
        email: "b122075@iiit-bh.ac.in",
        __v: 0,
        dataSet: true,
        imageSet: true,
        about: "I am Nikhil Rajpoot from jhansi (UP).I like to play cricket and chess,and love to enjoy every moment 💫💫💫\nI hope these four years of my life teaches me something good that's really helpful me...\n",
        city: "Jhansi ",
        id: "b122075",
        instagram: "nr_raja_",
        name: "Nikhil Rajpoot ",
        state: "Up",
        year: 1
    },
    {
        _id: "637dc8ea856b272166ca06eb",
        email: "b122076@iiit-bh.ac.in",
        __v: 0,
        about: "Music and learning from society ",
        city: "Kaimur ",
        dataSet: true,
        id: "b122076",
        imageSet: true,
        instagram: "Nishantkumar_560",
        name: "Nishant Kumar",
        state: "Bihar ",
        year: 1
    },
    {
        _id: "637df14d856b272166d8c99d",
        email: "b122077@iiit-bh.ac.in",
        __v: 0,
        dataSet: true,
        imageSet: true,
        about: "Hey GUYS I am Omkar Nanda.\nI am from Cuttack,Odisha.\nI like watching anime.",
        city: "Cuttack",
        github: "",
        id: "b122077",
        linkedin: "Https://LinkedIn.com/in/Omkar nanda",
        name: "Omkar nanda",
        state: "Odisha",
        year: 1,
        instagram: "Https://instagram.com/____omkar07"
    },
    {
        _id: "637d9b46856b272166b97c39",
        email: "b122078@iiit-bh.ac.in",
        __v: 0,
        dataSet: true,
        imageSet: true,
        about: "I am sriniketh, i am from Hyderabad i love technology, i play cricket, badminton and volleyball, i am a curious person",
        city: "Hyderabad ",
        id: "b122078",
        name: "Panuganti sriniketh ",
        state: "Telangana",
        year: 1
    },
    {
        _id: "6391c02b780e3003eac1acba",
        email: "b122079@iiit-bh.ac.in",
        __v: 0,
        dataSet: true,
        imageSet: true,
        about: "MY NAME IS DIVYAKUMAR PATEL\n",
        city: "Idar",
        id: "b122079",
        name: "DIVYAKUMAR PATEL",
        state: "Gujarat",
        year: 1
    },
    {
        _id: "637dc5e9856b272166c8d6aa",
        email: "b122080@iiit-bh.ac.in",
        __v: 0,
        dataSet: true,
        imageSet: true,
        about: "Hello everyone I am Piyali Purvasha Patnaik from Bhubaneswar,Odisha. I HAVE INTERESTS IN DANCING, PAINTING, ACTING AND TRAVELING. I am a fun LOVING and cheerful PERSON. I hope these four years turn out to be the best phase of my life. LOOKING forward to have a wonderful journey with you all.",
        city: "Bhubaneswar ",
        id: "b122080",
        instagram: "https://www.instagram.com/piyalipatnaik/",
        name: "Piyali Purvasha Patnaik ",
        state: "Odisha ",
        year: 1
    },
    {
        _id: "637d972c856b272166b7cc08",
        email: "b122081@iiit-bh.ac.in",
        __v: 0,
        dataSet: true,
        imageSet: true,
        about: "Hello EVERYONE, i am p.sai gopal from Orissa.I like to play cricket and kabbadi the MOST for get out from the strees and pressure.AND also play badminton and football NORMALLY.i love enjoy the nature and be happy always.\nThank you.\n",
        city: "GUNUPUR Dist-Rayagada ",
        id: "b122081",
        name: "Potnuru Sai Gopal ",
        state: "Orissa ",
        year: 1
    },
    {
        _id: "637e5353856b272166fed7cb",
        email: "b122082@iiit-bh.ac.in",
        __v: 0,
        dataSet: true,
        imageSet: true,
        about: "Hello everyone, I am Pragati Chatterjee.\nI want to explore more in my field.I do canvas and glass Paintings,read books.I love to enjoy nature.",
        city: "jharsuguda ",
        id: "b122082",
        name: "Pragati Chatterjee ",
        state: "Odisha ",
        year: 1
    },
    {
        _id: "637c756f856b2721665599ad",
        email: "b122083@iiit-bh.ac.in",
        __v: 0,
        dataSet: true,
        imageSet: true,
        about: "Hey there! A fellow techie here. Hobbies are VIDEO editing and gaming. ",
        city: "dhenkanal",
        id: "b122083",
        instagram: "https://instagram.com/_the_tranquil_lad",
        name: "Pranaya mallik",
        state: "odisha",
        year: 1
    },
    {
        _id: "637e5dee856b27216602ea24",
        email: "b122084@iiit-bh.ac.in",
        __v: 0,
        dataSet: true,
        imageSet: true,
        about: "The things that defines me is my curiosity and clarity in thoughts. I'm a travell freak and I have deep obesession with music.. hopping for a tremendous 4 years EXPERIENCE with all of you..",
        city: "Jajpur",
        id: "b122084",
        instagram: "https://www.instagram.com/priyabrata__nath/",
        name: "Priyabrata Nath",
        state: "Odisha",
        year: 1
    },
    {
        _id: "6395bd54780e3003eaf9a50e",
        email: "b122085@iiit-bh.ac.in",
        __v: 0,
        dataSet: true,
        imageSet: true,
        about: "I am pruthiraj , I believe in goal achieving, so make goal and try to achieve it with full potential. ",
        city: "Baleswer",
        id: "b122085",
        name: "Pruthiraj ",
        state: "Odisha",
        year: 1
    },
    {
        _id: "637d91b6856b272166b5a73a",
        email: "b122086@iiit-bh.ac.in",
        __v: 0,
        dataSet: true,
        imageSet: true,
        about: "I have just started to learn how to code and enjoying it. I like to play cricket a lot, wants to learn new skills",
        city: "Nalanda",
        id: "b122086",
        instagram: "https://www.instagram.com/i_m__r_a_j/",
        name: "Raj Mathur",
        state: "Bihar",
        year: 1
    },
    {
        _id: "637dcc72856b272166cb6d0f",
        email: "b122087@iiit-bh.ac.in",
        __v: 0,
        dataSet: true,
        imageSet: true,
        about: "Spend time with yourself....\nTrust the timing of your life !",
        city: "Bhubaneswar ",
        id: "b122087",
        instagram: "Http://instagram.com/_mr._.rajat_",
        name: "Rajat kiran sahu",
        state: "Odisha",
        year: 1
    },
    {
        _id: "637d9564856b272166b704c3",
        email: "b122088@iiit-bh.ac.in",
        __v: 0,
        dataSet: true,
        imageSet: true,
        about: "An optimistic PERSON,\nQuick LEARNER,\nLove to sing ",
        city: "Andapur ",
        id: "b122088",
        name: "Rajesh Kumar Jena ",
        state: "Odisha ",
        year: 1,
        linkedin: "https://www.linkedin.com/in/rajesh-kumar-jena-793257212",
        instagram: "https://instagram.com/kumar_rajesh_1234567?igshid=ZDdkNTZiNTM="
    },
    {
        _id: "637c499f856b272166459c5b",
        email: "b122089@iiit-bh.ac.in",
        __v: 0,
        dataSet: true,
        imageSet: true,
        about: "hayy everyone i'm ~rameez . want to become a software developer to develop many things ;)>>\nami'srk and cricketer \nand last thing is-\n'im born to express \nnot to impress__'",
        city: "GHAZIABAD ",
        id: "b122089",
        instagram: "https://instagram.com/rameezsiddiqui34?igshid=YmMyMTA2M2Y=",
        name: "RAMEEZ SIDDIQUI ",
        state: "UTTAR pradesh ",
        year: 1,
        linkedin: "https://www.linkedin.com/in/rameez-siddiqui-70416a258"
    },
    {
        _id: "637ddc32856b272166d15a4b",
        email: "b122090@iiit-bh.ac.in",
        __v: 0,
        dataSet: true,
        imageSet: true,
        about: "passionate to learn new skills, love to lead, good and interactive speaker, frindly and funny ",
        city: "bhubaneswar",
        id: "b122090",
        instagram: "https://www.instagram.com/reetam_nayak/",
        name: "Reetam kumar nayak",
        state: "odisha",
        year: 1
    },
    {
        _id: "639361dc780e3003ea47265b",
        email: "b122091@iiit-bh.ac.in",
        __v: 0,
        dataSet: true,
        imageSet: true,
        about: "HELLO EVERYONE 👏👏 MY NAME IS RISHABH VERMA. I LOVE TO PLAY CRICKET, CHESS and listening music. PLEASE FEEL FREE TO CONTACT ME, I WILL TRY TO HELP YOU IN MY FREE TIME. ",
        city: "Varanasi",
        id: "b122091",
        linkedin: "Https://LinkedIn.com/Rishabhverma",
        name: "Rishabh Verma",
        state: "Uttar  pradesh",
        year: 1
    },
    {
        _id: "637e168f856b272166e6e828",
        email: "b122092@iiit-bh.ac.in",
        __v: 0,
        about: "I am helpful and trustworthy in nature.\nI am a tech-geek and a cuber by passion.",
        city: "Balasore",
        dataSet: true,
        id: "b122092",
        imageSet: true,
        instagram: "https://instagram.com/rishav_chourasia402",
        linkedin: "https://www.linkedin.com/in/rishav-chourasia-169a33257",
        name: "Rishav Chourasia",
        state: "Odisha",
        year: 1
    },
    {
        _id: "637c336c856b2721663d759b",
        email: "b122093@iiit-bh.ac.in",
        __v: 0,
        about: "I have Keen Interest in COMPETITIVE  CODING🙃 and Cricket Yeah and I also like listening to rap and maybe sometimes  try to Do the same😅",
        city: "Bhubaneswar",
        dataSet: true,
        github: "HTTPS://GITHUB.COM/RISHITPARIJA",
        id: "b122093",
        imageSet: true,
        instagram: "HTTPS://Instagram.com/Rishitparija77",
        linkedin: "https://www.linkedin.com/in/rishit-parija-143a14247",
        name: "Rishit Parija",
        state: "Odisha",
        year: 1
    },
    {
        _id: "638f8406780e3003eac57027",
        email: "b122094@iiit-bh.ac.in",
        __v: 0,
        dataSet: true,
        imageSet: true,
        about: "I am Good at sports like badminton and KABADDI and in my free time i watch anime and MARVEL related series.\nQuite good at coding✌️",
        city: "Berhampur ",
        id: "b122094",
        instagram: "Https://instagram.com/Ritik patra",
        name: "Ritik patra ",
        state: "Odisha ",
        year: 1
    },
    {
        _id: "637d9856856b272166b848d4",
        email: "b122097@iiit-bh.ac.in",
        __v: 0,
        dataSet: true,
        imageSet: true,
        about: "Loving the life, enjoying the MOMENT\na cricket LOVER\nHave interest in SINGINg\nCan dance a little bit \n\n\n",
        city: "Indore ",
        id: "b122097",
        name: "Sachin Lovanshi ",
        state: "Madhya Pradesh ",
        year: 1,
        instagram: "https://www.instagram.com/sachin_love_vanshi/"
    },
    {
        _id: "6391c210780e3003eac2678e",
        email: "b122098@iiit-bh.ac.in",
        __v: 0,
        about: "I missed the part where that's my problem",
        city: "Hyderabad",
        dataSet: true,
        id: "b122098",
        imageSet: true,
        name: "SAMARASIMHA REDDY",
        state: "Telangana",
        year: 1
    },
    {
        _id: "637dc283856b272166c764cd",
        email: "b122100@iiit-bh.ac.in",
        __v: 0,
        dataSet: true,
        imageSet: true,
        about: "Hi myself Sarthak Mishra,I am from Bhubaneswar. Talking about my interests I like to code and read books . Currently I am learning web development and looking forward to explore more interesting stuff.",
        city: "BHUBANESWAR",
        id: "b122100",
        instagram: "https://www.instagram.com/sarthak_mishra_33/",
        name: "Sarthak Mishra ",
        state: "Odisha",
        year: 1
    },
    {
        _id: "637cb9d4856b2721666e2cb5",
        email: "b122102@iiit-bh.ac.in",
        __v: 0,
        dataSet: true,
        imageSet: true,
        about: "Hello everyone I'm Sashikanta Pattanaik from Jatni,odisha. Making these 4 years to be the best years in my life. Want to know me BETTER... Meet me.",
        city: "Jatni",
        id: "b122102",
        instagram: "https://instagram.com/sashikanta_pattanaik?igshid=ZDdkNTZiNTM=",
        name: "Sashikanta Pattanaik ",
        state: "Odisha",
        year: 1
    },
    {
        _id: "63930a42780e3003ea2a9568",
        email: "b122103@iiit-bh.ac.in",
        __v: 0,
        dataSet: true,
        imageSet: true,
        about: "I am passionate about learning and building technology. Playing sports,reading a good book,video editing are among the things i ENJOY.",
        city: "Bhubaneswar ",
        id: "b122103",
        name: "Saswat parasar behera",
        state: "odisha",
        year: 1
    },
    {
        _id: "637e4452856b272166f8bb5f",
        email: "b122104@iiit-bh.ac.in",
        __v: 0,
        about: "Simple, open minded, love to play chess and cricket...\n\nAs a Coding ENTHUSIASt, I always welcome advices...",
        city: "Bhubaneswar ",
        dataSet: true,
        id: "b122104",
        imageSet: true,
        instagram: "https://instagram.com/saswatpadhi2002?igshid=MWM2YjBjM2Q=",
        linkedin: "https://www.linkedin.com/in/saswat-padhi-88aa1a257",
        name: "Saswat Ranjan Padhi ",
        state: "Odisha",
        year: 1
    },
    {
        _id: "637df647856b272166daaac7",
        email: "b122105@iiit-bh.ac.in",
        __v: 0,
        dataSet: true,
        imageSet: true,
        about: "Selectively EXTROVERT 🌸",
        city: "Berhampur",
        id: "b122105",
        instagram: "HTTPS://instagram.com/Selina_sahu_",
        name: "Selina sahu",
        state: "Odisha",
        year: 1
    },
    {
        _id: "639235c9780e3003eae7f332",
        email: "b122106@iiit-bh.ac.in",
        __v: 0,
        about: "Hello everyone !!I am shivam(FROM ,JAUNPUR,UP). I love to play badminton,carrom board and cricket.please feel free to contact me,i will try to help you in my free time.",
        city: "jaunpur",
        dataSet: true,
        id: "b122106",
        imageSet: true,
        name: "shivam seth",
        state: "uttar pradesh",
        year: 1,
        linkedin: "https://LinkedIn.com/in/shivam seth"
    },
    {
        _id: "637e6976856b27216607224f",
        email: "b122108@iiit-bh.ac.in",
        __v: 0,
        dataSet: true,
        imageSet: true,
        about: "Conscious stardust on a mote of dust...",
        city: "DHENKANAL ",
        id: "b122108",
        name: "Shreeman Hrushikesh",
        state: "ODISHA ",
        year: 1,
        instagram: "https://www.instagram.com/lucid_.dream7/"
    },
    {
        _id: "637f977f856b2721666fb2f8",
        email: "b122109@iiit-bh.ac.in",
        __v: 0,
        about: "Hello!everyone I would like to introduce myself as a positive thinker who loves listening music and sometimes singing when vibe matches. I love watching Knowledgeable videos. Love programming. Love writing. ",
        city: "Kanpur",
        dataSet: true,
        id: "b122109",
        imageSet: true,
        instagram: "Https://Instagram.com/amishrey_g",
        name: "Shreyansh Gupta",
        state: "Uttar Pradesh",
        year: 1
    },
    {
        _id: "637f4876856b272166537991",
        email: "b122110@iiit-bh.ac.in",
        __v: 0,
        dataSet: true,
        imageSet: true,
        about: "Happiness can be found even in the darkest of times if one only remembers to turn on the light! ✨lumos maxima✨\n",
        city: "Berhampur",
        id: "b122110",
        name: "Shreyashi Panigrahy",
        state: "Odisha",
        year: 1
    },
    {
        _id: "637da60b856b272166bd604c",
        email: "b122111@iiit-bh.ac.in",
        __v: 0,
        dataSet: true,
        imageSet: true,
        about: "Hi mates, I'm shruti. I believe in learning and becoming better throughout life. I do MANDALA art, faceless portraits, hand lettering and art journaling. I'm also interested in graphic designing and digital ARTS and want to explore this field.",
        city: "Bhopal ",
        id: "b122111",
        instagram: "https://www.instagram.com/here.i_draw",
        name: "Shruti Vishwakarma",
        state: "Madhya Pradesh ",
        year: 1
    },
    {
        _id: "637d96c4856b272166b798ff",
        email: "b122112@iiit-bh.ac.in",
        __v: 0,
        about: "Treat people with kindness...\n\n",
        city: "Bhubaneswar ",
        dataSet: true,
        id: "b122112",
        imageSet: true,
        name: "Sipra Mohanty ",
        state: "Odisha",
        year: 1,
        instagram: "Http://instagram.com/_.s_2004_"
    },
    {
        _id: "637f3dfb856b2721664f8285",
        email: "b122113@iiit-bh.ac.in",
        __v: 0,
        dataSet: true,
        imageSet: true,
        about: "Hey! I am saloni.i am from BERHAMPUR,odisha.i like watching anime and reading manhwa.i too like writing STORIES.i believe in hard WORK.i strive to impress myself.",
        city: "Berhampur ",
        id: "b122113",
        name: "Saloni swarupa panda ",
        state: "Odisha",
        year: 1
    },
    {
        _id: "637df4eb856b272166da3060",
        email: "b122114@iiit-bh.ac.in",
        __v: 0,
        dataSet: true,
        imageSet: true,
        about: "hello guys soumil here. love to learn new thngs, hobbies include playing chess, badminton and watching anime. interests lie in ai and ml.",
        city: "Pune",
        id: "b122114",
        name: "Soumil Kumar",
        state: "maharashtra",
        year: 1
    },
    {
        _id: "639324f7780e3003ea336a1b",
        email: "b122115@iiit-bh.ac.in",
        __v: 0,
        dataSet: true,
        imageSet: true,
        about: "My self SUBHASHREE POLAI.my id is B122115.i am proud to be DAVIAN. I consider it's significant to LEARN AND BECOMe BETTER Through out. I spend my leisure time  sketching/drawing and getting creative with art MATERIALS.I'M ALSO INTERESTed in DIGITAL ARTS .",
        city: "Bhubaneswar",
        id: "b122115",
        name: "SUBHASHREE POLAI",
        state: "Odisha",
        year: 1
    },
    {
        _id: "637da52c856b272166bd0ccd",
        email: "b122116@iiit-bh.ac.in",
        __v: 0,
        about: "Hello, I am Subhradip Das. Singing is my passion. I have interest in politics and current affairs. ",
        city: "Englishbazar, malda",
        dataSet: true,
        id: "b122116",
        imageSet: true,
        instagram: "_subhradip_das_",
        linkedin: "https://www.linkedin.com/in/subhradip-das-82206523a",
        name: "Subhradip Das ",
        state: "West Bengal ",
        year: 1
    },
    {
        _id: "637c457a856b27216643edb2",
        email: "b122117@iiit-bh.ac.in",
        __v: 0,
        about: "Very much inclined towards sports and MUSIC especially SINGING. Badminton player but love football and CRICKET. ",
        city: "Cuttack",
        dataSet: true,
        id: "b122117",
        imageSet: true,
        instagram: "Https://Instagram.com/subhranshu599",
        name: "Subhranshu Panda",
        state: "Odisha ",
        year: 1
    },
    {
        _id: "6391c14e780e3003eac21c02",
        email: "b122118@iiit-bh.ac.in",
        __v: 0,
        dataSet: true,
        imageSet: true,
        about: "Sports enthusiast. Interested in research and development. Football fan. ",
        city: "Rourkela",
        id: "b122118",
        name: "Sudeep Kumar dehury",
        state: "Odisha",
        year: 1
    },
    {
        _id: "637df17b856b272166d8d916",
        email: "b122119@iiit-bh.ac.in",
        __v: 0,
        about: "My Hobby is making diy crafts.",
        city: "Angul ",
        dataSet: true,
        id: "b122119",
        imageSet: true,
        instagram: "https://www.instagram.com/sunayanxa",
        name: "SUNAYANA MUNDA ",
        state: "ODISHA ",
        year: 1
    },
    {
        _id: "637ce106856b2721667c9a4a",
        email: "b122120@iiit-bh.ac.in",
        __v: 0,
        dataSet: true,
        imageSet: true,
        about: "A simple girl with some simple dreams☺️\nLove to dance❤️\n",
        city: "Berhampur ",
        id: "b122120",
        name: "Sushree Subhashmita Mishra",
        state: "ODISHA",
        year: 1,
        instagram: "https://instagram.com/sush_ree18?igshid=YmMyMTA2M2Y="
    },
    {
        _id: "637c4fee856b27216647de10",
        email: "b122121@iiit-bh.ac.in",
        __v: 0,
        about: "Hey folks,this is swaroop.I like to play and WATch football.\nI love to play video games and ESPORTS .I can BEATBOx too :)\n",
        city: "Bargarh",
        dataSet: true,
        id: "b122121",
        imageSet: true,
        instagram: "https://www.instagram.com/Swaro_op007",
        name: "Swaroop darshan dash",
        state: "Odisha ",
        year: 1
    },
    {
        _id: "637bd24be5b4af03f7c4c12a",
        email: "b122122@iiit-bh.ac.in",
        __v: 0,
        dataSet: true,
        imageSet: true,
        about: "Hello Everyone, I am Swastik Gupta FROM first year B.tech CSE-B. My ID IS B122122. I HAVE COMPLETED MY 10TH FROM Baduria L.M.S High School and 12TH FROM Pathfinder Higher Secondary Public School. My hobbies are-Video EDITING ,photography,VIdeography,LISTENING MUSIC,Watching Anime. And also i have a little bit of interest in writing Rap-lyrics.\nThank you . ",
        city: "BADURIA,North 24 Pgs",
        id: "b122122",
        instagram: "https://instagram.com/lypophrenic_shiroko?igshid=NDk5N2NlZjQ=",
        name: "Swastik Gupta",
        state: "West Bengal ",
        year: 1
    },
    {
        _id: "637e4d10856b272166fc2584",
        email: "b122123@iiit-bh.ac.in",
        __v: 0,
        about: "Hi, I'm Swati.I'm an introvert. Like to listen music, reading & writing.I like to learn new things .",
        city: "Bhubaneswar",
        dataSet: true,
        id: "b122123",
        imageSet: true,
        name: "Swati Sundaray",
        state: "Odisha",
        year: 1
    },
    {
        _id: "637e562e856b2721660001f2",
        email: "b122125@iiit-bh.ac.in",
        __v: 0,
        dataSet: true,
        imageSet: true,
        about: "\nFOR(ALIVE)\n{\"LOVE TO CODE\"}\n",
        city: "Rourkela",
        github: "Https://github.com/tejaswee9316",
        id: "b122125",
        instagram: "https://instagram.com/_t.e.j.a.s.w.e.e_",
        name: "Tejaswee Kumar Singh ",
        state: "Odisha",
        year: 1
    },
    {
        _id: "637c4827856b272166450fad",
        email: "b122126@iiit-bh.ac.in",
        __v: 0,
        dataSet: true,
        imageSet: true,
        about: "Foodie here. I talk business.. ",
        city: "Mumbai",
        id: "b122126",
        instagram: "Https://Instagram.com/samarth.thaker07",
        linkedin: "Https://linkedin.com/samarththaker",
        name: "Samarth Thaker",
        state: "Maharashtra",
        year: 1
    },
    {
        _id: "63919ea7780e3003eab62911",
        email: "b122127@iiit-bh.ac.in",
        __v: 0,
        dataSet: true,
        imageSet: true,
        about: "Hi this is ursila. Love to explore new things. Love adventure. ",
        city: "Damanjodi,KORAPUT ",
        id: "b122127",
        instagram: "Https://instagram.Com/uru_lakra",
        name: "URSILA SIKHA LAKRA ",
        state: "Odisha",
        year: 1
    },
    {
        _id: "637dc0f5856b272166c6d527",
        email: "b122128@iiit-bh.ac.in",
        __v: 0,
        dataSet: true,
        imageSet: true,
        about: "Hello everyone, I'm Utsab Biswas. my hobby is doing sketches and I have certain interest in coding.",
        city: "Kolkata ",
        id: "b122128",
        instagram: "Https://instagram.com/lyadheshwar ",
        name: "UTSAB BISWAS",
        state: "West Bengal ",
        year: 1,
        linkedin: "https://www.linkedin.com/in/utsab-biswas-3958551bb/",
        github: "https://github.com/biswasutsab13"
    },
    {
        _id: "637e1b52856b272166e8f658",
        email: "b122129@iiit-bh.ac.in",
        __v: 0,
        about: "Hey I'm vaishno...I love to explore and learn new things...I have interest in writing...At last, \"rejection is all in your head\"...",
        city: "Bhubaneswar ",
        dataSet: true,
        id: "b122129",
        imageSet: true,
        name: "Vaishno Mahapatra ",
        state: "Orrisa",
        year: 1,
        instagram: "Https://instagram. Com/vaishno_07"
    },
    {
        _id: "639ca578780e3003ea2b6546",
        email: "b122130@iiit-bh.ac.in",
        __v: 0,
        dataSet: true,
        imageSet: true,
        about: "\n",
        city: "Gariyaband ",
        id: "b122130",
        name: "Vidya Rani Thakur ",
        state: "Chhattisgarh ",
        year: 1
    },
    {
        _id: "637c762a856b27216655e02e",
        email: "b122131@iiit-bh.ac.in",
        __v: 0,
        dataSet: true,
        imageSet: true,
        about: "Hello guys!!! I am Vishal.. I am A KEEN LEARNER AND EXPLORER, I am INTERESTED IN CODING AND RESEARCH, i LIKE TO PLAY VIDEO GAMES,and LOVe listening music..",
        city: "Motihari",
        id: "b122131",
        instagram: "HTTPS://instragram.COM/vishal_rauniyar30",
        linkedin: "https://www.linkedin.com/in/vishal-kumar-36305b258",
        name: "Vishal kumar",
        state: "bihar",
        year: 1
    },
    {
        _id: "637e200a856b272166eaf698",
        email: "b122132@iiit-bh.ac.in",
        __v: 0,
        dataSet: true,
        imageSet: true,
        about: "First year cse student at iiit Bhubaneshwar\nI am interested in WEB Development ",
        city: "Ahmedabad ",
        id: "b122132",
        name: "Yash nayak",
        state: "Gujrat ",
        year: 1
    },
    {
        _id: "6392deb2780e3003ea1c5934",
        email: "b122133@iiit-bh.ac.in",
        __v: 0,
        dataSet: true,
        imageSet: true,
        about: "In a world where you can be anything, be kind",
        city: "Kolkata",
        id: "b122133",
        instagram: "https://instagram.com/raika_zephaniah?igshid=YmMyMTA2M2Y=",
        name: "Zephaniah Raika",
        state: "West Bengal",
        year: 1,
        github: "https://github.com/zephaniah04"
    },
    {
        _id: "6391bd7b780e3003eac0a5b5",
        email: "b122134@iiit-bh.ac.in",
        __v: 0,
        about: "Currently Persuing my btech cse from Iiit Bhubaneswar. \nMy PASSION is to play electronic games and football\nMy interest is currently in \nDoing block chain development\n",
        city: "Bhubaneswar",
        dataSet: true,
        id: "b122134",
        imageSet: true,
        name: "ZULQUARnAIN KHAN",
        state: "Odisha",
        year: 1
    },
    {
        _id: "637edad4856b2721662b936d",
        email: "b122139@iiit-bh.ac.in",
        __v: 0,
        dataSet: true,
        imageSet: true,
        about: "hello everyone...\nI'm kifayat Yaseen Bhat.I'm From anantnag Kashmir. I'm very fond of cricket 🏏🏏 nd volleyball 🏐🏐\n",
        city: "anantnag",
        id: "b122139",
        name: "kifayat yaseen bhat",
        state: "jammu and kashmir",
        year: 1,
        instagram: "https://www.instagram.com/kifayatyasin/"
    },
    {
        _id: "637f4446856b27216651f4de",
        email: "b122140@iiit-bh.ac.in",
        __v: 0,
        dataSet: true,
        imageSet: true,
        about: "Hello everyone, I'm neeraj kumar. A goal oriented person, love to explore new things and interested in coding. really like to play cricket, VOLLEYBALL. A music enthusiastic,  love TO listen and write poems and songs lyrics. ",
        city: "Rajouri",
        id: "b122140",
        instagram: "http://instagram.com/neeraj07singh",
        name: "Neeraj Kumar",
        state: "Jammu and kashmir",
        year: 1
    },
    {
        _id: "6391c055780e3003eac1bca4",
        email: "b122141@iiit-bh.ac.in",
        __v: 0,
        dataSet: true,
        imageSet: true,
        about: "Hi everyone...",
        city: "Handwara",
        id: "b122141",
        name: "Arshiq bhat",
        state: "Jammu & kashmir",
        year: 1
    },
    {
        _id: "637f5f3a856b2721665bae14",
        email: "b122142@iiit-bh.ac.in",
        __v: 0,
        dataSet: true,
        imageSet: true,
        about: "Hello everyone I am from jammu.my hobbies are to play cricket , roller hockey and watch anime. beginner in coding. ;)",
        city: "Jammu",
        id: "b122142",
        instagram: "Https://instagram.com/_raghav_kohli_",
        name: "Raghav kohli",
        state: "Jammu and Kashmir",
        year: 1
    }
];

export default sampleData