const sampleData = [
    {
        _id: "637d9683856b272166b77af8",
        email: "b122001@iiit-bh.ac.in",
        __v: 0,
        dataSet: true,
        imageSet: true,
        about: "Hello EVERYONE 👋👋 , I am abhik . I do have lots of interests in coding , PHOTOGRAPHY, and exploring New technologies and Would love to explore these in My college life . I love to play cricket and badminton. PLEASE feel free to contact me any TIME through my given handles . Would be happy to help anyone in leisure time . ",
        city: "Bhubaneswar",
        id: "b122001",
        name: "Abhik sundar sahu",
        state: "Odisha ",
        year: 1,
        instagram: "https://instagram.com/abhiksahu3092?igshid=YmMyMTA2M2Y=",
        linkedin: "https://www.linkedin.com/in/abhik-sundar-sahu-262179258",
        github: "https://github.com/Abhiksahu3092"
    },
    {
        _id: "638f7fe9780e3003eac41bf1",
        email: "b122002@iiit-bh.ac.in",
        __v: 0,
        dataSet: true,
        imageSet: true,
        about: "Hello everyone!! I am Abhimanyu. I love playing football,table tennis and chess.i am an ntse scholar and have a decent academic record.i also have keen Interest in debating and public speaking.hoping to learn,grow and have fun in these 4 years with you all.",
        city: "patna",
        id: "b122002",
        name: "Abhimanyu Kumar singh",
        state: "bihar",
        year: 1
    },
    {
        _id: "637d96af856b272166b78f86",
        email: "b122004@iiit-bh.ac.in",
        __v: 0,
        about: "YOU MAY CALL ME AS THE GURGAON WALA ODIA TOka. I HAVE A KEEN INTEREST IN CRICKET. AND PLAY TABLA OCASSIONALLY. Always Happpy to Help. ",
        city: "Bhubaneswar ",
        dataSet: true,
        id: "b122004",
        imageSet: true,
        name: "Abinas Ojha ",
        state: "Odisha",
        year: 1,
        instagram: "Https://instagram.com/abinas.ojha.264"
    },
    {
        _id: "63923429780e3003eae76be8",
        email: "b122006@iiit-bh.ac.in",
        __v: 0,
        about: "Hello everyone 👋👋, I am Adarsh. I have lots OF interest in coding and reading books. I love to play chess and cricket.",
        city: "Kanpur",
        dataSet: true,
        id: "b122006",
        imageSet: true,
        name: "Adarsh tiwari",
        state: "Uttar PRADESH",
        year: 1,
        linkedin: "HTTPS://LINKEDIN.COM/ADARSH TIWARI"
    },
    {
        _id: "637c4780856b27216644c776",
        email: "b122008@iiit-bh.ac.in",
        __v: 0,
        dataSet: true,
        imageSet: true,
        about: "🎮 Gamo-sapien🕹\nComic geek 👓 \nFootball ⚽⚽ lover \nWho doesn't like anime\n",
        city: "Berhampur ",
        id: "b122008",
        instagram: "https://instagram.com/ashen_aditya?igshid=NmQ2ZmYxZjA=",
        name: "Aditya Narayan",
        state: "Odisha ",
        year: 1,
        github: "https://github.com/aditARAN",
        linkedin: "https://www.linkedin.com/in/aditya-narayan-8b40b0258"
    },
    {
        _id: "637f2dfc856b27216649e55b",
        email: "b122009@iiit-bh.ac.in",
        __v: 0,
        dataSet: true,
        imageSet: true,
        about: "Bonjour fellas!A heliophile dis side.My hobbies include dancing, journaling, playing guitar, badminton,chess and reading books.WOULD love to know about you too!",
        city: "Cuttack",
        id: "b122009",
        name: "Adyasha mohanty",
        state: "Odisha",
        year: 1,
        instagram: "addyctive.16"
    },
    {
        _id: "637d91cd856b272166b5ae6d",
        email: "b122010@iiit-bh.ac.in",
        __v: 0,
        about: "Hello 👋,  I am akash bharti. My id is B122010. I am from ranchi. My hobbies are watching movies and playing games and f1. Not much😅",
        city: "RANCHI",
        dataSet: true,
        id: "b122010",
        imageSet: true,
        linkedin: "https://www.linkedin.com/in/akash-bharti-56598b199",
        name: "Akash bharti",
        state: "JHARKHAND",
        year: 1,
        instagram: "https://www.instagram.com/invites/contact/?i=90mn0ljguule&utm_content=pa5w4od"
    },
    {
        _id: "637dc908856b272166ca16ff",
        email: "b122011@iiit-bh.ac.in",
        __v: 0,
        dataSet: true,
        imageSet: true,
        about: "Kudos! Myself Akshat bankey…..an average weeb and a gamer with hobbies including football and table tennis.",
        city: "Mumbai",
        id: "b122011",
        instagram: "https://instagram.com/bankeyboi._",
        name: "Akshat bankey",
        state: "Maharashtra",
        year: 1
    },
    {
        _id: "637c526e856b27216648da52",
        email: "b122012@iiit-bh.ac.in",
        __v: 0,
        dataSet: true,
        imageSet: true,
        about: "I have keEn interest in photography,videography,editing,coding,and sports😊😊\n\n\n\n\n\nint main(){\n    Cout<<“hello everyone!!<<endl;\n}",
        city: "Delhi",
        id: "b122012",
        instagram: "https://www.instagram.com/_aman_raY_",
        name: "AMAN RAY",
        state: "Delhi",
        year: 1
    },
    {
        _id: "637dcc8a856b272166cb7742",
        email: "b122013@iiit-bh.ac.in",
        __v: 0,
        dataSet: true,
        imageSet: true,
        about: "Hi, my name is Amarendra Das and I come from a middle-class village background. I have a great aim in technology and am passionate about achieving my goals. Despite facing many failures, I remain resilient and determined to succeed.",
        city: "DHENKANAL",
        id: "b122013",
        name: "Amarendra das ",
        state: "ODISHA",
        year: 1,
        linkedin: "https://www.linkedin.com/in/amarendra-das-5548aa25a"
    },
    {
        _id: "637ee8be856b27216630483a",
        email: "b122014@iiit-bh.ac.in",
        __v: 0,
        dataSet: true,
        imageSet: true,
        about: "Hello,I am amisha Ray.my id is b122014.i have interest in listening to music,travelling and watching movies.",
        city: "Bhubaneswar ",
        id: "b122014",
        instagram: "__amisha_ray__",
        name: "Amisha ray",
        state: "Odisha",
        year: 1
    },
    {
        _id: "637e1e5a856b272166ea3e7e",
        email: "b122015@iiit-bh.ac.in",
        __v: 0,
        dataSet: true,
        imageSet: true,
        about: "Intuitive, curious and a learner. My motto - \"take it live it.\" Interests in basketball 🏀 and also a writer. I am rather intrigued by phenomenal happenings.be a event and everyone will be looking forward to you 👒",
        city: "angul",
        id: "b122015",
        instagram: "https://www.instagram.com/am_13_it/",
        linkedin: "https://www.linkedin.com/in/amit-kumar-73a257258",
        name: "Amit kumar behera",
        state: "odisha",
        year: 1
    },
    {
        _id: "637dca8e856b272166caa8f1",
        email: "b122016@iiit-bh.ac.in",
        __v: 0,
        dataSet: true,
        imageSet: true,
        about: "Live young live free....",
        city: "Bhubaneshwar",
        id: "b122016",
        instagram: "HTTPS://INSTAGRAM.COM/routamit572 ",
        name: "Amit Kumar Rout ",
        state: "ODISHA",
        year: 1
    },
    {
        _id: "637d9693856b272166b78388",
        email: "b122017@iiit-bh.ac.in",
        __v: 0,
        dataSet: true,
        imageSet: true,
        about: "Ready to learn and EXPLORE.like to play volleyball and a huge football fan.\n\nAdios.✌️",
        city: "Jharsuguda ",
        id: "b122017",
        name: "Anand Naik",
        state: "Odisha",
        year: 1,
        instagram: "Https://instagram.com/_ANDY_nic_"
    },
    {
        _id: "637c521c856b27216648ba18",
        email: "b122018@iiit-bh.ac.in",
        __v: 0,
        dataSet: true,
        imageSet: true,
        about: "Hi EVERYBODY, I am Anirudh. A guy having a keen interest in watching movies, TRAVELLING, listening to PODCASTS and writing programs in the mean time... \nWANNA know more about me?! HERE are my handles.",
        city: "Jaipur ",
        id: "b122018",
        name: "Anirudh Pradhan ",
        state: "Rajasthan ",
        year: 1,
        instagram: "https://www.instagram.com/_.anirudh.roshan._/",
        linkedin: "https://www.linkedin.com/in/anirudh-pradhan-a2ab25245"
    },
    {
        _id: "637e0676856b272166e0ac9c",
        email: "b122019@iiit-bh.ac.in",
        __v: 0,
        about: "Always be happy\n",
        city: "Haldia",
        dataSet: true,
        id: "b122019",
        imageSet: true,
        instagram: "https://instagram.com/showd259?igshid=Njc5ZjliZWU=",
        name: "Ankan barik",
        state: "West bengal",
        year: 1
    },
    {
        _id: "637e1fe0856b272166eae55a",
        email: "b122020@iiit-bh.ac.in",
        __v: 0,
        dataSet: true,
        imageSet: true,
        about: "When they try to burn you down with a couple of matches, \nJust remember you're a Phoenix rising from the ASHES!! ",
        city: "Howrah",
        id: "b122020",
        instagram: "https://instagram.com/simply._sophisticated?igshid=YmMyMTA2M2Y=",
        name: "Ankit Gourisaria",
        state: "West Bengal",
        year: 1
    },
    {
        _id: "637dceb2856b272166cc5241",
        email: "b122021@iiit-bh.ac.in",
        __v: 0,
        about: "hola!!\ni am An ambivert and an explorer who loves to perceive a unique way to introduce life...\n",
        city: "cuttack",
        dataSet: true,
        id: "b122021",
        imageSet: true,
        instagram: "J_ankita12",
        linkedin: "ankita jena",
        name: "ankita jena",
        state: "odisha",
        year: 1
    },
    {
        _id: "637f199e856b272166426bcb",
        email: "b122022@iiit-bh.ac.in",
        __v: 0,
        dataSet: true,
        imageSet: true,
        about: "Learning, observing, and connecting the dots",
        city: "Bhawanipatna ",
        id: "b122022",
        instagram: "https://instagram.com/anushkajoshi301?igshid=YmMyMTA2M2Y=",
        name: "Anushka Joshi",
        state: "Odisha ",
        year: 1
    }
];

export default sampleData